name: Generate Pacman Graph
on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight
  workflow_dispatch:       # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-contribution-pacman@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
